Shreya Mohan code for code review. To be merged to DEV_Shreya.
Stevens-SSE/wordle-group-e pull request #5
Opened 2022-04-11 18:58 UTC by smohan98

Hello Shivani and Tirth,
Please review my code for the Code review assignment.

Thanks.

2022-04-12 04:36 UTC, Tirth-Patel903 reviewed
Note:- unable to add comments in some file . 
1. Not able to run code not even getting error.
2. Less Comments there is comment only for modules so there is no logical comments which is helpful.
3. One Code which runs successfully but I got error in that.
4. Variable names are not appropriate to the logic.
5. Good thing is every code has try and except available.
6. Design patterns are not up to the mark in some code tried to save lines due to that having problem in reading code its looks like mixed code.
7. Test file has no comments variable names are not make sense 
8. All code is not understandable and also there is no comments and variable names are not related to logic so its hard to understand actual code.
9. One thing that is cool I think every assignment has different code and file so easy get track in mine I had same file for every assignment.

2022-04-13 22:02 UTC, smaurya30 requested changes

2022-04-13 22:02 UTC, smaurya30 commented on HW09_Shreya_Mohan_helper.py
> +        return good, bad, correct
Proper variables and function names made understanding the code easier

2022-04-13 22:02 UTC, smaurya30 commented on HW07_Shreya_Mohan_statistics.py
> +        return letters
Missing Exception Handling

2022-04-19 18:59 UTC, merged