Tirth patel
Stevens-SSE/wordle-group-e pull request #6
Opened 2022-04-12 04:17 UTC by Tirth-Patel903

Hey, Shreya and Shivani I have raised request Now you can review my code.

2022-04-13 19:56 UTC, smohan98 commented on letter_frequency.py
> +        playAgain=messagebox.askquestion("Confirm","Do You Want To Play Again?")
MessageBox is a good implementation but from a user's point of view it doesn't work well to see input in one place and output on the terminal

2022-04-13 19:58 UTC, smohan98 commented on letter_frequency.py
> +        staticals_list.pop(0)
Rather than using pop 6 times you can just do this : staticals_list[5:]

2022-04-13 19:59 UTC, smohan98 commented on letter_frequency.py
> +        a = open("demo.txt", "w")
For code to be readable for other developers use better naming convention

2022-04-13 20:01 UTC, smohan98 commented on letter_frequency.py
> +    print(sorted_list)
Unnecessary print statements should not be a part of this PR

2022-04-13 20:01 UTC, smohan98 commented on letter_frequency.py
> +    print(tupleDict)
Unnecessary print statements should not be a part of this PR

2022-04-13 20:03 UTC, smohan98 commented on letter_frequency.py
> +    logger.info('Your guessing percentage:-'+str(distribution))
Logs are a developer facing entity and should be written in a correct format
 ```
User Input :: INFO  :: info message
 User Input :: WARNING  :: warn message
 User Input :: ERROR    :: error message
 User Input :: CRITICAL :: critical message
```

2022-04-13 20:05 UTC, smohan98 commented on test_wordle.py
> +        self.assertEqual(WordleGame.processGuess(self,guess,answer),True,"test_process Test failed")
```suggestion
        self.assertEqual(WordleGame.processGuess(self,guess,answer),True,"test_process_same_guess Test failed")

```

2022-04-13 20:08 UTC, smohan98 commented on wordle.py
> +            staticals_list.pop(0)
Rather than using pop 6 times you can just do this : staticals_list[5:]

2022-04-13 20:09 UTC, smohan98 commented on wordle.py
> +            if playAgain == 'yes':
Boolean Flags supersed any other datatype flags, its good practice to use Booleans

2022-04-13 20:10 UTC, smohan98 commented on wordle.py
> +        pos=""
```suggestion
        clue,hint,pos="","",""

```

2022-04-13 20:12 UTC, smohan98 commented on wordle.py
> +                pos=str(position) +','
```suggestion
                pos=f"{position},"

```

2022-04-13 20:13 UTC, smohan98 commented on wordle.py
> +                    if (line[0] == theAnswer[0]) and (line[4] == theAnswer[4]):
```suggestion
                    if line[0] == theAnswer[0] and line[4] == theAnswer[4]:

```

2022-04-13 20:14 UTC, smohan98 commented on wordle.py
> +            print(linked_list)
Unnecessary print statements should not be a part of this PR

2022-04-13 20:27 UTC, smohan98 commented on wordle.py
> +            return theGuess
```suggestion
        return theGuess

```

2022-04-13 20:31 UTC, smohan98 commented on letter_frequency.py
> +                        freq[item]=citem
So many if else is a bruteforce solution and can easily be avoided by a dictionary implementation

2022-04-13 20:33 UTC, smohan98 commented on letter_frequency.py
> +        ROOT = tk.Tk()
Can be replaced by from tkinter import TK

2022-04-13 20:34 UTC, smohan98 commented on letter_frequency.py
> +        return theGuess
```suggestion
    return theGuess
```

2022-04-13 20:45 UTC, smohan98 reviewed
Following are some comments and suggestions I have about this PR:

- Most importantly the code is not at all segregated in files, 1 file code is a very unacceptable way to write code by industry standards
- No function has a docstring
- Code is not readable for a new developer to understand easily
- File names in python don't follow camel casing, they should follow '_' separated names
- Too many unnecessary print statements in the code
- Message box implementation not a good idea in this case as user will be forced to have two windows open( i.e. the terminal for result and input box for input)
- Logging needs to be improved to understand errors and pinpoint problems if occurred
- Variable naming should not be single letters but rather should be a self descriptive
- Boolean flags should be used for conditional loops and not 'yes' and 'no'
- Majority functions lack try catch loops to catch errors if any
- Test file should have better messages for test failures
- Some of the code follows Python2 standards and some follows Python3
- Too many Bruteforce solutions are implemented

Pros:
- Although the use-case doesn't suit here, input box is an impressive implementation
- Comments are present before some logics
-  Functions are present for even small small cases to be reused

2022-04-13 22:21 UTC, smaurya30 requested changes

2022-04-13 22:21 UTC, smaurya30 commented on wordle.py
> +        f.close()
close() function can be added in finally blocks in case an exception occurs

2022-04-13 22:21 UTC, smaurya30 commented on letter_frequency.py
> +def main():
Functions need to be added to a class for OOP requirement

2022-04-13 22:21 UTC, smaurya30 commented on test_wordle.py
> +    def test_process(self):
Good job on the test cases, most of them are covered

2022-04-13 22:21 UTC, smaurya30 commented on letter_frequency.py
> +        playAgain=messagebox.askquestion("Confirm","Do You Want To Play Again?")
Agree with @smohan98

2022-04-13 22:21 UTC, smaurya30 commented on wordle.py
> +            staticals_list.pop(0)
Can use clear() instead of pop() 6 times for emptying the list

2022-04-13 22:21 UTC, smaurya30 commented on wordle.py
> +            if playAgain == 'yes':
Agree with @smohan98

2022-04-13 22:21 UTC, smaurya30 commented on wordle.py
> +        return clue == "GGGGG" #True if correct,False otherwie
Missing Exception Handling

2022-04-13 22:21 UTC, smaurya30 commented on wordle.py
> +        array_hintt=[]
Missing Exception Handling

2022-04-15 18:23 UTC, Tirth-Patel903 commented on letter_frequency.py
> +        playAgain=messagebox.askquestion("Confirm","Do You Want To Play Again?")
Yes, but I want GUI best so this is implemented by me. Thanks for suggestions.

2022-04-15 18:23 UTC, Tirth-Patel903 commented on letter_frequency.py
> +        staticals_list.pop(0)
I done this change you can review it, Thanks.

2022-04-15 18:24 UTC, Tirth-Patel903 commented on letter_frequency.py
> +        a = open("demo.txt", "w")
changed this you can check

2022-04-15 18:24 UTC, Tirth-Patel903 commented on letter_frequency.py
> +    print(sorted_list)
removed this print statement you can review.

2022-04-15 18:25 UTC, Tirth-Patel903 commented on wordle.py
> +            staticals_list.pop(0)
This changed to suggested you can check.

2022-04-15 18:26 UTC, Tirth-Patel903 commented on wordle.py
> +            if playAgain == 'yes':
This is inbuild functionality for boolean there is another function in tkinter but I used this . Thanks but can't change.

2022-04-15 18:26 UTC, Tirth-Patel903 commented on wordle.py
> +        pos=""
changed suggested code thanks.

2022-04-15 18:27 UTC, Tirth-Patel903 commented on wordle.py
> +                pos=str(position) +','
changed suggested code, thanks.

2022-04-15 18:27 UTC, Tirth-Patel903 commented on wordle.py
> +            print(len(hint))
removed this thanks

2022-04-15 18:29 UTC, merged